### ISSUE TITLE
Timeline in Compare Seiyuu not sorted by release date

### ISSUE THREAD

**Issue by colorfusion** [Ervie/Seiyuu.moe#1]
As written in the title, the timeline tab in the compare seiyuu page is not sorted by release date of the anime. The design might be correct based on implementation, but having the anime displayed in the order of their release date seems more logical for a timeline.

**Comment by Ervie** [comment]
You can change the timeline direction via clicking on arrow on timeline, but you have a point. Saw the PR, I should merge and redeploy it tomorrow.

**Comment by colorfusion** [comment]
Thanks for replying! Clicking on the arrow does reverse the order, but the date wasn't in the right order to begin with due to the dates in the sort function not being parsed properly.

This is a pretty great app! Being able to see the connections between the seiyuus and animes! 👍

**Comment by Ervie** [comment]
Updated version is deployed.

Thanks for kind words! I plan to add more functionalities (listed in "Projects" tab on this repo page), but currently a fell a bit burnt out to work on the side project. Such words encourage to back working on that :)

Also I found a bug in season summary, preventing to displays some seasons, I will try to fix it in a few days.
